name: Semantic release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          NPM_TOKEN: ${{ secrets.NPM }}
        run: npx semantic-release
