name: Semantic release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build-storybook
      - name: Publish
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
